server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: ms-productos
              uri: lb://ms-productos
              predicates:
                - Path=/api/productos/**
            - id: ms-pedidos
              uri: lb://ms-pedidos
              predicates:
                - Path=/api/pedidos/**