server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-productos
          uri: lb://ms-productos
          predicates:
            - Path=/api/productos/**
        - id: ms-pedidos
          uri: lb://ms-pedidos
          predicates:
            - Path=/api/pedidos/**
        - id: oauth-server
          uri: lb://oauth-server
          predicates:
            - Path=/oauth2/**
  