spring:
  application:
    name: ms-productos

  r2dbc:
    url: ${DB_URL_PRODUCTOS_QA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  main:
    web-application-type: reactive

server:
  port: 8081
  error:
    include-message: always

logging:
  level:
    org.springframework.r2dbc: DEBUG

eureka:
  instance:
    prefer-ip-adress: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/